# Generated by Django 2.2.24 on 2021-08-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_apartment_main_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='infomation',
            new_name='information',
        ),
    ]
