# Generated by Django 2.2.24 on 2021-08-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenu',
            name='test',
        ),
    ]
