# Generated by Django 2.2.24 on 2021-08-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0002_remove_mainmenu_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('title', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
