# Generated by Django 2.2.24 on 2021-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
